Document: elfres
Title: Debian elfres Manual
Author: <insert document author here>
Abstract: This manual describes what elfres is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/elfres/elfres.sgml.gz

Format: postscript
Files: /usr/share/doc/elfres/elfres.ps.gz

Format: text
Files: /usr/share/doc/elfres/elfres.text.gz

Format: HTML
Index: /usr/share/doc/elfres/html/index.html
Files: /usr/share/doc/elfres/html/*.html
